In [1]:
import math
rad = math.atan2(3,2)
th = math.degrees(rad)
th

56.309932474020215

In [2]:
# ベクトルの演算
import numpy as np
a = np.array([2,2])
b = np.array([2, -1])
a + b
             

array([4, 1])

In [3]:
a - b

array([0, 3])

In [4]:
2 * a

array([4, 4])

In [5]:
from sympy import Symbol, solve
a = Symbol('a')
b = Symbol('b')

ex1 = -1*a + b - 2
ex2 = 2*a + b - 4
solve((ex1, ex2))


{a: 2/3, b: 8/3}

In [6]:
10 * math.cos(math.radians(60))

5.000000000000001

In [7]:
10 * math.cos(math.radians(30))

8.660254037844387

In [16]:
10 * math.cos(math.radians(89))

-0.17452406437283477

In [15]:
10 * math.cos(math.radians(90))

0.174524064372836

In [17]:
10 * math.cos(math.radians(90))

6.123233995736766e-16

In [12]:
10 * math.cos(math.radians(180))

-10.0

In [13]:
10 * math.cos(math.radians(360))

10.0

In [19]:
a = np.array([2, 7])
b = np.array([6, 1])
c = np.array([2, 3])
d = np.array([6, 5])

# ベクトルa
va = b - a

# ベクトルb
vb = d - c

# ベクトルの大きさ 3平方の定理
norm_a = np.linalg.norm(va)
norm_b = np.linalg.norm(vb)

# ベクトルの内積
dot_ab = np.dot(va, vb)

# 角度
cos_th = dot_ab / (norm_a * norm_b)

# cosの逆関数
rad = math.acos(cos_th)
deg = math.degrees(rad)
deg


82.8749836510982

In [20]:
a = np.array([2,4])
b = np.array([3,1])

# 外積
cross_ab = np.cross(a, b)
s = np.linalg.norm(cross_ab)
s / 2

5.0